### PR TITLE
Fix search

### PR DESCRIPTION
**Pull request by hfittipaldi**
The search plugin is not working properly when you search for the exact expression

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks. Can you please convert the spaces to tabs. Like that the pr can't being reviewed.

**Comment by hfittipaldi** [comment]
No problem.

**Comment by laoneo** [comment]
Sorry, but going directly to the database is not the way to go. The model should being used for that. Can you tell us what exactly is not working?

**Comment by hfittipaldi** [comment]
Well, the model does not make the distinction between "all words", "any word" and "exact phrase" that user chooses. It explodes the searchTerms anyway. So, it was easier modify the plugin (I adapted it from the joomla search content plugin) than modify the model.

**Comment by laoneo** [comment]
The other problem is that then search does only work for local events and not external ones like from Google Calendar, Facebook events, iCloud or MS Exchange.

**Pull request closed without merging**
